import React, { useState, useEffect } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { TextField, Button, Typography, Box, Alert } from "@mui/material";
import LockIcon from "@mui/icons-material/Lock";
import GlassCard from "../components/GlassCard";
import { useAuth } from "../routes/AuthContext";
import { useDispatch } from "react-redux";
import {
  loginFailure,
  loginStart,
  loginSuccess,
} from "../redux/slices/authSlice";
import { verify2FALogin } from "../services/authService";

const Verify2FA = () => {
  const location = useLocation();
  const navigate = useNavigate();
  const dispatch = useDispatch();
  // const {user, setUser} = useAuth();
  // Extract the temporary token passed from the login credentials check
  const { tempToken, email } = location.state || {};

  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [loading, setLoading] = useState(false);

  // console.log("user", user);
  console.log("error", error);
  console.log("success", success);

  // Crash prevention: Redirect to login if token is missing
  useEffect(() => {
    if (!tempToken) {
      navigate("/login", {
        state: { alertMessage: "Session expired. Please log in again." },
      });
    }
  }, [tempToken, navigate]);

  const handleChange = (e) => {
    const val = e.target.value;
    // Permit digits only and max length of 6
    if (/^\d*$/.test(val) && val.length <= 6) {
      setCode(val);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (code.length !== 6) {
      setError("Verification code must be exactly 6 digits.");
      return;
    }

    setError("");
    setLoading(true);

    try {
      dispatch(loginStart());
      const res = await verify2FALogin(code, tempToken);

      console.log("2FA verification response:", res.data);
      if (res.data.success) {
        // setUser(res.data.user);
        dispatch(loginSuccess({ user: res.data.user, token: res.data.token }));
        setError("");
        setSuccess("Authentication approved! Redirecting...");

        setTimeout(() => {
          navigate("/dashboards");
        }, 1500);
      }
    } catch (err) {
      dispatch(loginFailure());
      console.log("2FA verification error:", err.response?.data || err.message);
      setError(
        err.response?.data?.message || "Verification failed. Please try again.",
      );
    } finally {
      setLoading(false);
    }
  };

  if (!tempToken) return null;

  return (
    <Box
      sx={{
        display: "flex",
        justifyContent: "center",
        minHeight: "90vh",
        alignItems: "center",
      }}
    >
      <GlassCard>
        <Box sx={{ textAlign: "center" }} mb={3}>
          <LockIcon sx={{ fontSize: 40, color: "#a855f7", mb: 1 }} />
          <Typography
            variant="h5"
            sx={{ fontFamily: "Outfit", fontWeight: 800 }}
          >
            2FA Verification
          </Typography>
          <Typography variant="body2" color="textSecondary" mb={1}>
            Enter the 6-digit code generated by your Authenticator app for:
          </Typography>
          <Typography
            variant="body2"
            sx={{ color: "#a855f7", fontWeight: "bold" }}
          >
            {email}
          </Typography>
        </Box>

        {error && (
          <Alert
            severity="error"
            sx={{
              mb: 3,
              background: "rgba(239, 68, 68, 0.1)",
              color: "#ff8a8a",
              border: "1px solid rgba(239, 68, 68, 0.2)",
            }}
          >
            {error}
          </Alert>
        )}

        {success && (
          <Alert
            severity="success"
            sx={{
              mb: 3,
              background: "rgba(16, 185, 129, 0.1)",
              color: "#a7f3d0",
              border: "1px solid rgba(16, 185, 129, 0.2)",
            }}
          >
            {success}
          </Alert>
        )}

        <form onSubmit={handleSubmit}>
          <TextField
            fullWidth
            label="Verification Code"
            variant="outlined"
            className="custom-textfield"
            value={code}
            onChange={handleChange}
            placeholder="e.g. 123456"
            disabled={loading}
            inputProps={{
              maxLength: 6,
              inputMode: "numeric",
              style: {
                textAlign: "center",
                letterSpacing: "0.3em",
                fontSize: "1.2rem",
                fontFamily: "monospace",
              },
            }}
          />

          <Button
            type="submit"
            fullWidth
            variant="contained"
            className="custom-btn"
            disabled={loading || code.length !== 6}
            sx={{ mt: 3, mb: 1 }}
          >
            {loading ? "Verifying..." : "Log In"}
          </Button>
        </form>
      </GlassCard>
    </Box>
  );
};

export default Verify2FA;
